# Site settings
title:       Java Snippets
description: > # this means to ignore newlines until "baseurl:"
  VERY BASIC snippets of code that I find myself using all the time. Maybe they are useful for you too? Who knows.
  Each snippet is inside a folder and has a main program. Sometimes there are other classes too.
  There is a Commons folder for the common methods used by all of them. They are defined as static inside a final class.
baseurl:     "" # the subpath of your site, e.g. /blog/
url:         "http://javasnippets.tk" # the base hostname & protocol for your site
exclude:     [ .gitignore, css/nyanya.png, css/NyaNya.ai _layouts/cover.html, contacts.html, dukeWaveRed.gif ]

#User names
twitter_username: octopusinvitro
git_username:     octopusinvitro
git_repo:         java-snippets

# Build settings
markdown: kramdown
sass:
  style: compressed

